### ISSUE TITLE
Turkish Language Translations

### ISSUE THREAD

**Issue by Mersaultkn** [turtlecoin/turtlecoin.lol#43]
Hi there,  I try to translate en.yml to tr.yml, there it is, can u check? 
```
[tr.txt](https://github.com/turtlecoin/turtlecoin.lol/files/2069397/tr.txt)

# Common
contact:
  interested: Projemiz ile ilgileniyor musunuz?
  need_help: Bize Katılın! Bize Yardım Edin! Yetkinliğiniz ne olursa olsun! Fikirleriniz, görüşleriniz ve varlığınız ile bize destek olun! Size ihtiyacımız var!
  discord: Discord kanalımıza katılın
  github: GitHub Sayfamızı inceleyin
  thank_you: Teşekkür ederiz!
  scroll_up: Yukarı

navbar:
  home: Anasayfa
  download: Yüklemeler
  features: Farklılıklar
  story: Hikayetmiz
  specs: Gözlem
  roadmap: Yol Haritası
  support: Destek
  toggle_navigation: Menü
  resources: Kaynaklar
  resources_wiki: TurtleCoin Kitaplığı
  resources_blog: Geliştirici Bloğu
  resources_dev_resources: Geliştirici Kaynakları
  resources_brand: Marka Kullanımı


# Pages

# https://turtlecoin.lol/
index_page:
  meta:
    description: TurtleCoin sizlere hem iş hem de bireysel para gönderiminin eğlenceli ve kişisel gizliliğe önem veren bir yolunu sunuyor. TurtleCoin TurtleCoin topluğu tarafından geliştirilen açık kaynaklı, masaüstü cüzdana sahip, kolay kazılabilen yeni nesil bir kriptoparadır.
    title: TurtleCoin.lol - TurtleCoin Eğlenceli, Hızlı ve Kullanıcı Dostu Kriptopara.

  # banner section
  banner_is_fast: TurtleCoin Hızlıdır
  banner_is_easy: TurtleCoin Kullanıcı Dostudur
  banner_is_safe: TurtleCoin Güvenlidir
  banner_one_liner: TurtleCoin arkadaşlarınız ve ticari ilişkileriniz için <br/> Para göndermenin, Eğlenceli, Hızlı ve Güvenli yolunu sunuyor.
  banner_download: Yükle
  banner_builds: <strong>Windows, Apple ve Ubuntu Linux için hazır uygulamalarımızı kullanabilirsiniz.</strong>Eğer <strong>kaynak kodlar</strong>ımıza ulaşmak istiyorsanız, <a href="https://github.com/turtlecoin/turtlecoin/">GitHub</a> sayfamızı ziyaret edebilirsiniz, Ayrıca bize dilediğiniz zaman <a href="http://chat.turtlecoin.lol"> ulaşarak </a> aramıza katılabilirsiniz .

  # download section
  download_select_system: İşletim Sisteminizi Seçin
  download_latest: Güncel versiyonu indir
  download_gui: Masaüstü uygulamayı indir
  download_cli: Komut istemi uygulamasını indir

  # fun facts section
  fun_facts_title: Turtle Artıları
  fun_facts_1: TurtleCoin 30 saniyelik blok süresine yani yüksek hızlı transfer imkanına sahiptir.
  fun_facts_2: TurtleCoin özel blockchain üzerinde çalışmaktadır. Sizden başka hiç kimse paranızı göremez.
  fun_facts_3: Görüntüleme ve Harcama anahtarlarınız ile silinen bir cüzdanı kolaylıkla kurtarabilirsiniz

  # why section
  why_title: Neden TurtleCoin?
  why_1_title: Hızlı Transfer
  why_1: TurtleCoin her 30 saniyede bir yeni blok oluşturmaktadır. Bitcoin veya BitcoinCash a oranla 20 kat hızlı transfer imkanı sağlamaktadır.
  why_2_title: Gizlilik
  why_2: TurtleCoin Monero ve Aeon ile aynı gizlilik özelliklerini sunmaktadır. Gönderimleriniz siz aksini belirlemedikçe gizli ve takip edilemez olur.
  why_3_title: Kolay Kullanım
  why_3: Mobil de dahil olmak üzere hemen hemen tüm işletim sistemlerini destekliyoruz <a href="https://turtlecoin.lol/wallet"> Ücretsiz paper wallet</a>, oluşturarak 5 dakikadan daha kısa süre içerisinde TurtleCoin'e katılabilirsiniz.
  why_4_title: Kolay Kazım
  why_4: TurtleCoin cpu ( İşlemci ) temel kazım aracı ile birlikte gelmektedir, dilerseniz Monero kazımını destekleyen diğer kazım araçlarını da hem cpu hem gpu olarak kullanabilirsiniz,  <a href="https://github.com/fireice-uk/xmr-stak/releases/latest">XMR-Stak</a> yazılımını bu işlemler için önermekteyiz.
  why_5_title: Topluluk
  why_5: TurtleCoin topluluğu tüm kullanıcı ve geliştiricilerin katılımına açıktır. Fikir ve görüşlerinize değer veriyoruz. Topluluğumuza katılmak için <a href="http://chat.turtlecoin.lol">Discord</a> kanalımıza bekliyoruz.
  why_6_title: Destek
  why_6: Sürekli büyüyen yazılımcı ve test ekibi ailesi  <a href="http://meta.turtlecoin.lol">GitHub meta-forum</a> platformumuzu ziyaret edebilirsiniz. Bize tester olarak ya da hata raporlayıcısı olarak katkıda bulunabilirsiniz.

  # the story section
  story_title: Hikayemiz
  story_1: Arka Plan
  story_2: Çoğu Turtlecoin geliştiricisi kalın tatlı sakallara sahiptir. <strong>Gerçekten...</strong></h3>
  story_3: <em>Bu bize yeteneklerimiz, düşünmemiz ve saygınlığımızda <strong> fazladan 10 çene tutma puanı </strong> kazandırır. <i class="far fa-smile"></i></em>
  story_4: Gerçek şu ki çoğumuz tam zamanlı başka projeler ile ilgilenen ama bu eğlenceli topluluğa katkı sağlamak için bir araya gelmiş geliştiricileriz.
  story_5: Nasıl Başladık?
  story_6: Soğuk bir Aralık gecesi RockSteady ve Bebop birlikte biralarını yudumlarken, sayıları gittikçe artan gerçek bir proje dahi sunmayan sahte ve başarısız ICOlar hakkında konuşuyorlardı. Bebop işini ciddiye alan bir ekip gerçekçi bir pazarlama ve ciddi bir finansman olmadan gerçek bir proje çıkartmanın mümkün olmadığı kanısına vardı. 
  story_7: RockSteady eğildi sakalını dikkatle okşadı ve tek bir cevap verdi...
  story_8: <strong>"Biramı tutar mısın?."</strong>
  story_9: O gece, 9 Aralık 2017 tarihinde, TurtleCoin doğdu.
  story_10: Neden mi?
  story_11: Çoğu proje herhangi bir ürüne sahip olmadan önce çok fazla fon topluyor. "Neden tüm her şeyi tersten yapmıyoruz?" diye düşündük, işe eğlenceli bir ürün hazırlayarak başlayıp, mümkün olduğunca basit ve erişilebilir hale getirip, kendi kendine büyümesine izin verdik.
  story_12: Finansman stratejimizin güçlü yanı <strong>Eğer havalı bir ürün ortaya çıkartırsak ürünün ihtiyaç duyacağı değer kendi kendine oluşacaktır.</strong> Bu konuda yanıldığımızı düşünüyorsanız görüşlerinizi dinlemekten mutluluk duyarız <a href="http://meta.turtlecoin.lol">bize yazın</a>.
  story_13: Bilge bir fare bir keresinde , "Bir kampumbağa sadece boynunu dışarı çıkartarak ilerler.."
  story_14: alıntı

  # fine print section
  fine_print_title: Hızlı Bilgilendirmeler
  fine_print_1: Proje hakkında kısa bilgiler.
  fine_print_2: Ortalama Blok Ödülü
  fine_print_3: 1 Blok üretimi <br> 30 saniye
  fine_print_4: Geliştiriciler <br> <a href="http://chat.turtlecoin.lol">Bize Katılın</a>
  fine_print_5: Ön Kazım <br> Geliştirici Payı

  # roadmap section
  roadmap_title: Yol Haritası
  roadmap_1: Merhaba Turtle
  roadmap_2: TurtleCoin Doğdu <strong>9 Aralık 2017</strong>.
  roadmap_3: Başlangıçta sadece komut satırında ve Linux üzerinde çalışıyorduk. Flash barındıran çevrimiçi platformlardan yasaklandık.
  roadmap_4: Masaüstü Cüzdan
  roadmap_5: "TurtleCoin topluluğu olarak İlk günden itibaren TurtleCoin'i daha kolay hale getirme konusunda kararlıyız ve bu da iyi bir Masaüstü uygulaması ile mümkün. Bu nedenle Masaüstü cüzdan uygulamamız üzerinde yoğun bir şekilde çalıştık. Aynı şekilde komut satırı cüzdan uygulamamızı da geliştirdik. Sonuç olarak aşağıdaki Cüzdan uygulamalarını seçmeniz için size sunduk:"
  roadmap_6: Pazar Antlaşmaları
  roadmap_7: 2018'in 2. çeyreğinden itibaren TurtleCoin'in halka açık olduğunu ilan ettik. Pek çok yeni pazar için girişimlerimiz devam ediyor. 
  roadmap_8: Geliştirmelerin başlaması, 2018 2. Çeyrek
  roadmap_9: Topoloji, Hızlı ve Senkronize gerekliliği olmayan Bloklar
  roadmap_10: Büyük bir zinciri senkronize etmek blok hızı farketmeksizin sıkıcı ve uzun zaman alan bir uğraş oluyor. Hedefimiz daha kısa bir zincir ile hızlı blok yapısını kullanıp bu sorunu çözmek. Bu zorlu hedefi gerçekleştirmek için gittikçe artan bir ekip ile çalışıyoruz. 
  roadmap_11: Gelecekte Duyurulacak
  roadmap_12: Karai, Basit Akıllı Kontratlar
  roadmap_13: Dağıtılmış, güvenilir olmayan ağların para biriminin ötesinde kullanım alanları bulunur. Karai, ana blok zincirinin ötesinde dağıtılmış uygulamaların ve ağların etkinleştirilmesine yönelik çalışmamızdır.
  roadmap_14: TurtlePay Ağı
  roadmap_15: Yakınlarınızda bulunmayan bir ATM ne işinize yarar? Dokun ve öde geçmişte kaldı, Artık Dokun ve kazan var. En yakın Kripto ATM'si cebinizde!.


# https://turtlecoin.lol/brand/
brand_page:
  meta:
    description: TurtleCoin Marka Kitapçığı
    title: TurtleCoin | Brand Kullanım Klavuzu
  why: Klavuza Neden Gerek var?
  why_explanation: TurtleCoin ile harika şeyler yapmak isteyen herkesin bu bilgilere erişimi olması gerektiğine inanıyoruz. Bu amaçla, sizin TurtleCoin markasıyla birleşen fikirlerinizi ifade etmeniz için <strong>tutarlı ve güçlü</strong>, aynı zamanda <strong>samimi ve kolay</strong> bir yaklaşım yolu sağlamak için bir dizi kılavuz oluşturduk .
  download: Karşıdan İndir
  manual: TurtleCoin Marka Klavuzu
  latest_version: Güncel Versiyon
  download_assets: İndirme Seçenekleri
  contribute_on_github: GitHub'da Katkı Sağlayın

brand_page_navbar:
  guidelines: Klavuzlar
  assets: Seçenekler
  join: Bize Katılın
  back: Anasayfaya Dönün
```
